.\" Manpage for i3hloc
.TH man 1 "04-08-2017" "1.0" "i3hloc man page"
.SH NAME
i3hloc - JSON data streamer for i3bar written in Haskell
.SH SYNOPSIS
i3hloc [ARGS]
.SH DESCRIPTION
i3hloc is a simple data display for i3bar writeen in Haskell. It uses custom rcf format for configuration.
.SH OPTIONS
-h, --help - displays help

--printDefaultConfig - prints default config to stdin

-i - installs used config in default directory (.config/i3hloc)

-c <FILE> - uses <FILE> as config

-d - uses default configuration

.SH CONFIGURATION
i3hloc uses custom .rcf config format, which is similar to .ini with some exceptions. Like in typical .ini file it contains one or more sections which consist of:

- a header, which stands for name of section. It is surrounded by square brackets

- sequence of fields

Every .rcf file must begin with main section with 'blocks' field. It is has to be string list names of displayed blocks in order.

.SH TYPING

rcf is statically weak typed. It means you are forced to explicitly write type declaration for all variables, and they must match what program expects. There are 5 main types: int, float, char, bool and string, and one parametrised list type.

Lists are declared using pattern

.B list:type name = {elements,separated,by,comma}

Examples of some valid declarations:

.B string field = yes

.B list:bool alist = {true, True, false,False}

Strings may be defined as normal literals (the will be read until end of line). Another way is to surround text by "|  |"
quotes, eg.


string text = "| this

is a valid string |"


Escape signs (using "\\") are currently not supported.

.SH AVAILABLE FIELDS

You may use these fields in any sections

.B string prefix
- prefix to be added before displayed text

.B string suffix
- suffix to be added after displayed text

.B string color
- color of the text.
Color is read in 8bit format, eg.
.B #ff44cc

.B string bgcolor
- background color

.B string underline
- underline mode. There are several modes available:
.B none, single, double, error

.SH "TYPE" FIELD
Every section must have string type field with one of following values:

.B command
- for execution custom system command. It requires string command value for name of command to be executed and optional string stdin for stdin input, list:string args for program arguments and string iomode for what you want to gain: stdout, stderr, retcode (default stdout)

.B volume
- displays volume using amixer

.B bandwidth
- displays network usage for given interface (string). Requires period (float) field as period between updates.

.B battery
- displays battery state using acpi

.B Time
- displays current time. Requires string format field that describes format of displayed data. You may use any signs here. First character after '%' will describe information to be displayed: s - seconds, m - minutes, h - hour in 12 format, H - hour in 24 format, d - day of month, Y - year, y - year modulo 100, W - full week day name, w - short week day name, a - am or pm. Eg.: string format =  %d-%M-%Y

.SH EXAMPLES
You can see example configuration when you run i3hloc with --printDefaultConfig flag

.SH BUGS
Config parsing may suck
.SH AUTHOR
Radosław Rowicki
