name:                i3hloc
version:             0.1.0.0
github:              "radrow/i3hloc"
license:             BSD3
author:              "Radosław Rowicki"
maintainer:          "radrowicki@gmail.com"
copyright:           "2019 Radosław Rowicki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Flexible scheduler for i3bar
category:            Utils

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/radrow/i3hloc#readme>

dependencies:
- base >= 4.7 && < 5
- clock
- directory
- font-awesome-type
- process
- split
- text
- json
- bytestring
- containers
- trifecta
- mtl
- time
- transformers

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  i3hloc:
    main:                Main.hs
    source-dirs:         i3hloc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - i3hloc
